import type { AgentSetupPayload } from "@/lib/onboard-agent";

const video = "https://videos.pexels.com/video-files/7578545/7578545-uhd_1440_2732_25fps.mp4";

export const PILOT_AGENTS: AgentSetupPayload[] = [
  {
    slug: "maya",
    name: "Maya Chen",
    market: "Austin, TX",
    neighborhoods: [
      "East Austin",
      "South Congress",
      "Mueller",
      "Hyde Park",
      "Zilker",
      "Tarrytown",
      "Cherrywood",
      "Bouldin Creek"
    ],
    headshotUrl:
      "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=600&q=80",
    bio: "Austin buyer specialist with a calm eye for value and livability.",
    phone: "+15125550141",
    email: "maya@example.com",
    closedVolumeUsd: 84_000_000,
    buyersPlaced: 127,
    accentColor: "#C97B5C",
    listings: [
      {
        isPocket: true,
        address: "1811 Willow Creek Drive",
        price: 725000,
        beds: 3,
        baths: 2,
        sqft: 1810,
        neighborhood: "East Austin",
        property_type: "house",
        features: ["yard", "updated_kitchen", "walkable"],
        dealBreakerFlags: ["busy_street"],
        videoUrl: video,
        videoSource: "mp4",
        agent_note:
          "Kitchen's dated but the bones are incredible; easy reno and this feels like a much bigger buy.",
        description: "Pocket three-bed near coffee, trails, and the east-side restaurant corridor."
      },
      {
        address: "5204 Berkman Terrace",
        price: 642000,
        beds: 3,
        baths: 2.5,
        sqft: 1665,
        neighborhood: "Mueller",
        property_type: "townhouse",
        features: ["garage", "walkable", "updated_kitchen"],
        dealBreakerFlags: ["hoa", "shared_walls"],
        videoUrl: video,
        videoSource: "mp4",
        agent_note: "Very easy daily life here; the HOA is real, but the location earns it.",
        description: "Bright townhome steps from Mueller parks, shops, and weekly farmers market."
      },
      {
        address: "404 E 45th Street",
        price: 875000,
        beds: 4,
        baths: 3,
        sqft: 2310,
        neighborhood: "Hyde Park",
        property_type: "house",
        features: ["home_office", "quiet_street", "yard"],
        dealBreakerFlags: [],
        videoUrl: video,
        videoSource: "mp4",
        agent_note: "The office is the quiet win; it actually works for two remote schedules.",
        description: "Classic Hyde Park home with shaded yard and separate work-from-home nook."
      },
      {
        address: "2109 Bluebonnet Lane",
        price: 1185000,
        beds: 4,
        baths: 3.5,
        sqft: 2860,
        neighborhood: "Zilker",
        property_type: "house",
        features: ["pool", "yard", "open_floor_plan"],
        dealBreakerFlags: [],
        videoUrl: video,
        videoSource: "mp4",
        agent_note: "This is the entertaining house; expensive, but it uses every square foot well.",
        description: "Contemporary Zilker home with pool, open kitchen, and wide indoor-outdoor flow."
      },
      {
        address: "1312 Travis Heights Boulevard",
        price: 934000,
        beds: 3,
        baths: 2,
        sqft: 1985,
        neighborhood: "South Congress",
        property_type: "house",
        features: ["walkable", "updated_kitchen", "quiet_street"],
        dealBreakerFlags: [],
        videoUrl: video,
        videoSource: "mp4",
        agent_note: "Rarely do you get this much calm this close to South Congress.",
        description: "Low-slung home tucked off South Congress with updated finishes and mature trees."
      },
      {
        address: "706 Cherrywood Road",
        price: 689000,
        beds: 3,
        baths: 2,
        sqft: 1575,
        neighborhood: "Cherrywood",
        property_type: "house",
        features: ["yard", "home_office", "quiet_street"],
        dealBreakerFlags: ["fixer_upper"],
        videoUrl: video,
        videoSource: "mp4",
        agent_note: "Needs cosmetic love, but the floor plan is honest and the street is sweet.",
        description: "Cherrywood bungalow with a small office, fenced yard, and approachable price."
      },
      {
        address: "1908 Bouldin Avenue",
        price: 799000,
        beds: 2,
        baths: 2,
        sqft: 1420,
        neighborhood: "Bouldin Creek",
        property_type: "condo",
        features: ["walkable", "updated_kitchen", "garage"],
        dealBreakerFlags: ["shared_walls", "hoa"],
        videoUrl: video,
        videoSource: "mp4",
        agent_note: "A strong lock-and-leave option if you care more about location than yard.",
        description: "Polished Bouldin Creek condo with garage parking and a short walk to dining."
      },
      {
        address: "2507 Enfield Road",
        price: 1100000,
        beds: 4,
        baths: 3,
        sqft: 2740,
        neighborhood: "Tarrytown",
        property_type: "house",
        features: ["yard", "quiet_street", "home_office"],
        dealBreakerFlags: [],
        videoUrl: video,
        videoSource: "mp4",
        agent_note: "Not flashy, but the lot and schools make it a long-term hold.",
        description: "Tarrytown family home with deep yard, flexible office, and quiet frontage."
      },
      {
        address: "3001 Manor Road",
        price: 512000,
        beds: 2,
        baths: 1.5,
        sqft: 1190,
        neighborhood: "East Austin",
        property_type: "condo",
        features: ["walkable", "new_construction"],
        dealBreakerFlags: ["hoa", "busy_street"],
        videoUrl: video,
        videoSource: "mp4",
        agent_note: "Best for someone who wants east-side access and can tolerate the road noise.",
        description: "Newer two-bed condo near restaurants, transit, and east Austin nightlife."
      }
    ]
  },
  {
    slug: "david",
    name: "David Park",
    market: "Seattle, WA",
    neighborhoods: [
      "Ballard",
      "Queen Anne",
      "Capitol Hill",
      "Fremont",
      "Green Lake",
      "Wallingford",
      "Columbia City",
      "West Seattle"
    ],
    headshotUrl:
      "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=600&q=80",
    bio: "Seattle advisor for practical buyers who care about commute and resale.",
    phone: "+12065550155",
    email: "david@example.com",
    closedVolumeUsd: 63_000_000,
    buyersPlaced: 94,
    accentColor: "#7A8F6A",
    listings: [
      {
        isPocket: true,
        address: "1421 NW 61st Street",
        price: 910000,
        beds: 3,
        baths: 2.5,
        sqft: 1885,
        neighborhood: "Ballard",
        property_type: "house",
        features: ["yard", "garage", "updated_kitchen"],
        dealBreakerFlags: [],
        videoUrl: video,
        videoSource: "mp4",
        agent_note: "Quiet pocket of Ballard, and the garage is more useful than it looks online.",
        description: "Off-market Ballard craftsman with refreshed kitchen and fenced backyard."
      },
      {
        address: "517 Galer Street",
        price: 1245000,
        beds: 4,
        baths: 3,
        sqft: 2510,
        neighborhood: "Queen Anne",
        property_type: "house",
        features: ["home_office", "quiet_street", "garage"],
        dealBreakerFlags: [],
        videoUrl: video,
        videoSource: "mp4",
        agent_note: "The hill is real, but the light and office setup are worth seeing.",
        description: "Queen Anne home with city views, dedicated office, and two-car garage."
      },
      {
        address: "812 E Pike Street",
        price: 685000,
        beds: 2,
        baths: 2,
        sqft: 1095,
        neighborhood: "Capitol Hill",
        property_type: "condo",
        features: ["walkable", "updated_kitchen"],
        dealBreakerFlags: ["hoa", "shared_walls", "busy_street"],
        videoUrl: video,
        videoSource: "mp4",
        agent_note: "Fun location, but I'd only push it for someone who likes energy outside.",
        description: "Updated Capitol Hill condo close to restaurants, rail, and nightlife."
      },
      {
        address: "3630 Evanston Avenue N",
        price: 845000,
        beds: 3,
        baths: 2.5,
        sqft: 1620,
        neighborhood: "Fremont",
        property_type: "townhouse",
        features: ["home_office", "walkable", "new_construction"],
        dealBreakerFlags: ["shared_walls"],
        videoUrl: video,
        videoSource: "mp4",
        agent_note: "A townhouse that lives bigger than expected; the top-floor work nook helps.",
        description: "Newer Fremont townhouse with rooftop deck and flexible work space."
      },
      {
        address: "7028 5th Avenue NE",
        price: 1075000,
        beds: 4,
        baths: 2.5,
        sqft: 2325,
        neighborhood: "Green Lake",
        property_type: "house",
        features: ["yard", "quiet_street", "garage"],
        dealBreakerFlags: [],
        videoUrl: video,
        videoSource: "mp4",
        agent_note: "This is the steady choice: good block, usable yard, simple resale story.",
        description: "Green Lake home on a calm street with garage and sunny backyard."
      },
      {
        address: "4412 Wallingford Avenue N",
        price: 965000,
        beds: 3,
        baths: 2,
        sqft: 1760,
        neighborhood: "Wallingford",
        property_type: "house",
        features: ["walkable", "yard", "updated_kitchen"],
        dealBreakerFlags: [],
        videoUrl: video,
        videoSource: "mp4",
        agent_note: "The layout is clean, and Wallingford buyers will understand it later.",
        description: "Updated Wallingford home with a practical main floor and private patio."
      },
      {
        address: "3715 S Edmunds Street",
        price: 735000,
        beds: 3,
        baths: 2,
        sqft: 1540,
        neighborhood: "Columbia City",
        property_type: "house",
        features: ["yard", "walkable", "quiet_street"],
        dealBreakerFlags: ["fixer_upper"],
        videoUrl: video,
        videoSource: "mp4",
        agent_note: "Some projects, yes, but the location and lot are doing the heavy lifting.",
        description: "Columbia City home near light rail with yard and renovation upside."
      },
      {
        address: "4721 42nd Avenue SW",
        price: 795000,
        beds: 3,
        baths: 2.5,
        sqft: 1690,
        neighborhood: "West Seattle",
        property_type: "townhouse",
        features: ["garage", "walkable", "open_floor_plan"],
        dealBreakerFlags: ["shared_walls"],
        videoUrl: video,
        videoSource: "mp4",
        agent_note: "Alaska Junction convenience without giving up parking, which matters here.",
        description: "West Seattle townhouse with garage, open living, and Junction access."
      },
      {
        address: "214 N 76th Street",
        price: 585000,
        beds: 2,
        baths: 1,
        sqft: 980,
        neighborhood: "Green Lake",
        property_type: "condo",
        features: ["walkable", "updated_kitchen"],
        dealBreakerFlags: ["hoa", "shared_walls"],
        videoUrl: video,
        videoSource: "mp4",
        agent_note: "Small but sharp; this is about getting into Green Lake without stretching.",
        description: "Efficient Green Lake condo with updated kitchen and easy lake access."
      }
    ]
  }
];
